apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: ezp9e5cu5-python 
  janus-idp.io/tekton: ezp9e5cu5-python
  backstage.io/kubernetes-id: ezp9e5cu5-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: ezp9e5cu5-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml